image:
  file: Dockerfile

tasks:
  - command: psql postgres && \c some_database && \i .\setup_postgres.sql && dotnet run --urls http://0.0.0.0:5001

ports:
  - port: 5000
    onOpen: ignore
  - port: 5001
    onOpen: open-preview

  
