image:
  file: Dockerfile

ports:
  - port: 5000
    onOpen: ignore
  - port: 5001
    onOpen: open-preview
    
tasks:
  - init: psql -h localhost -d postgres --file=setup_postgres.sql

  - name: Postinstall .NET 6.0 and dev certificates
    init: |
      mkdir -p /tmp/dotnet && curl -fsSL https://dot.net/v1/dotnet-install.sh | bash /dev/stdin --channel 6.0 --install-dir /tmp/dotnet 
      dotnet dev-certs https 
      dotnet restore
